# Generated by Django 5.1.3 on 2024-12-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('result', models.BooleanField()),
            ],
        ),
    ]
